version: "3.8"

services:
  middleware_odoo:
    build:
      context: ./docker-config
      args:
        APP_NAME: middleware_odoo
    container_name: middleware_odoo
    volumes:
      - /home/oddo-users/www/middleware_odoo:/var/www/html/middleware_odoo
    networks:
      - mynetwork
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8070:8071"
    container_name: middleware_odoo_nginx
    volumes:
      - /home/oddo-users/www/middleware_odoo:/var/www/html/middleware_odoo
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge
